/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ManejoDeArchivos.BibliotecaCRUD;
import ManejoDeArchivos.EdificioCRUD;
import epn.com.biblioteca.Biblioteca;
import epn.com.biblioteca.Edificio;
import epn.com.biblioteca.Libro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
   
    
/**
 *
 * @author Thony
 */
public class MenuBibliotecario extends javax.swing.JFrame {
    private EdificioCRUD edificioCrud = new EdificioCRUD();
    private BibliotecaCRUD bibliotecaCrud = new BibliotecaCRUD(); 
    private Biblioteca biblioteca = new Biblioteca(); 
    private Edificio edificio = new Edificio(); 
    private VentanaRegistro ventanaRegistro; 
    DefaultTableModel mt = new DefaultTableModel(); 
    /**
     * Creates new form MenuBibliotecario
     */
    public MenuBibliotecario() {
        initComponents();
        String ids [] = {"Titulo", "Autor", "Codigo","Disponible"};
        mt.setColumnIdentifiers(ids);
        jTableDataLibros.setModel(mt);
        actualizarInfoComboBox();
    }
   
    public void actualizarInfoComboBox(){
        jCBiblio.removeAllItems(); 
        List <Biblioteca> biliotecas = bibliotecaCrud.listarBibliotecas(); 
        if (biliotecas.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se encuentran bibliotecas registradas");
        } else {
            for (Biblioteca b : biliotecas){
                jCBiblio.addItem(b.getNombre());
            }
        }
    }
    
    public void mostrarLibrosBiblioSeleccionada(){
        String nombreBiblio = (String) jCBiblio.getSelectedItem(); 
        if (nombreBiblio == null || nombreBiblio.isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecciona una biblioteca válida");
            return; 
        }
        List <Biblioteca> bibliotecas =bibliotecaCrud.listarBibliotecas();
        boolean encontrada = false; 
        for (Biblioteca b : bibliotecas){
            if (b.getNombre().trim().equalsIgnoreCase(nombreBiblio)){
                cargarDatosEnTabla(b.getLibros());
                encontrada = true; 
                break; 
            }
        }
        if (!encontrada){
            JOptionPane.showMessageDialog(null, "No se encontraron libros para la biblioteca seleccionada");
        }
    }
    
    public void cargarDatosEnTabla(List <Libro> libros){
        mt.setRowCount(0);
        for (Libro l : libros){
            mt.addRow(new Object[]{
                l.getTitulo(), l.getAutor(),
                l.getCodigo(), l.isDisponible() ? "Si" : "No"
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNombreBiblio = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTMetrosCuadrados = new javax.swing.JTextField();
        jTUbiEdificio = new javax.swing.JTextField();
        jCTipoBiblio = new javax.swing.JComboBox<>();
        jBGuardar = new javax.swing.JButton();
        jBAgregarEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataLibros = new javax.swing.JTable();
        jBAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCBiblio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Biblioteca");

        jLabel2.setText("Nombre de la biblioteca");

        jLabel3.setText("Tipo");

        jLabel4.setText("Direccion");

        jLabel5.setText("Metros cuadrados");

        jLabel6.setText("Ubicacion del edificio");

        jCTipoBiblio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sleccione un tipo...", "Pública", "Privada" }));

        jBGuardar.setText("Añadir Biblioteca");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBAgregarEliminar.setText("Eliminar libros");
        jBAgregarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarEliminarActionPerformed(evt);
            }
        });

        jTableDataLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDataLibros);

        jBAgregar.setText("Agregar Libros");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jLabel7.setText("Selecciona la biblioteca ");

        jCBiblio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTNombreBiblio)
                                            .addComponent(jTDireccion)
                                            .addComponent(jTMetrosCuadrados)
                                            .addComponent(jTUbiEdificio)
                                            .addComponent(jCTipoBiblio, 0, 140, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jBAgregar)
                                        .addGap(34, 34, 34)
                                        .addComponent(jBAgregarEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCTipoBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTMetrosCuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTUbiEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBAgregarEliminar)
                    .addComponent(jBAgregar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBiblio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        String nombreBiblio = jTNombreBiblio.getText(); 
        String tipoBiblio = (String) jCTipoBiblio.getSelectedItem();
        String direccion = jTDireccion.getText(); 
        double metrosCuadrados = Double.parseDouble(jTMetrosCuadrados.getText()); 
        String ubiEdi = jTUbiEdificio.getText(); 
        
        if(nombreBiblio.isEmpty() || tipoBiblio.isEmpty() || direccion.isEmpty() ||
                ubiEdi.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No pueden haber campos vacíos");
                    return;       
        }
        Edificio nuevoEdificio = new Edificio(ubiEdi, metrosCuadrados); 
        Biblioteca nuevaBiblio = new Biblioteca(nombreBiblio, tipoBiblio, direccion, edificio);         
        edificioCrud.agregarEdificio(nuevoEdificio);
        bibliotecaCrud.agregarBiblioteca(nuevaBiblio);        
        JOptionPane.showMessageDialog(this, "Informacion de la biblioteca guardada");
        
        jTNombreBiblio.setText("");
        jCTipoBiblio.setSelectedIndex(0);
        jTDireccion.setText("");
        jTMetrosCuadrados.setText("");
        jTUbiEdificio.setText("");
        
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String  nombreBiblio = (String) jCBiblio.getSelectedItem(); 
        if (nombreBiblio == null || nombreBiblio.isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione una biblioteca válida");
            return;
        }
         String titulo = JOptionPane.showInputDialog("Escribe el titulo del libro"); 
         String autor = JOptionPane.showInputDialog("Escribe el autor del libro");
         String codigo = JOptionPane.showInputDialog("Escribe el codigo del libro"); 
         
         if (titulo == null || autor == null || codigo == null){
             JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
             return; 
         }
         
        Libro libroNuevo = new Libro(titulo, autor, codigo, true); 
        
        List <Biblioteca> bibliotecas = bibliotecaCrud.listarBibliotecas(); 
        for (Biblioteca b : bibliotecas){
            if (b.getNombre().equalsIgnoreCase(nombreBiblio)){
                b.getLibros().add(libroNuevo); 
                bibliotecaCrud.agregarBiblioteca(b);
                JOptionPane.showMessageDialog(null, "Libro agregado correctamente");
                cargarDatosEnTabla(b.getLibros());
                return; 
            }
        }
        
        JOptionPane.showMessageDialog(null, "No se encontró la biblioteca");
        
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBAgregarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarEliminarActionPerformed
        int filaSeleccionada = jTableDataLibros.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un libro en la tabla para eliminar");
        return;
        }

        String codigoLibro = (String) jTableDataLibros.getValueAt(filaSeleccionada, 2); 
        String nombreBiblio = (String) jCBiblio.getSelectedItem();

        List<Biblioteca> bibliotecas = bibliotecaCrud.listarBibliotecas();
        for (Biblioteca b : bibliotecas) {
            if (b.getNombre().equalsIgnoreCase(nombreBiblio)) {
                List<Libro> libros = b.getLibros();
                boolean eliminado = libros.removeIf(l -> l.getCodigo().equalsIgnoreCase(codigoLibro));
                if (eliminado) {
                    bibliotecaCrud.agregarBiblioteca(b);  
                    cargarDatosEnTabla(libros);
                    JOptionPane.showMessageDialog(this, "Libro eliminado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el libro");
            }
            return;
        }
    }

        JOptionPane.showMessageDialog(this, "No se encontró la biblioteca");
    }//GEN-LAST:event_jBAgregarEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAgregarEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<String> jCBiblio;
    private javax.swing.JComboBox<String> jCTipoBiblio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTMetrosCuadrados;
    private javax.swing.JTextField jTNombreBiblio;
    private javax.swing.JTextField jTUbiEdificio;
    private javax.swing.JTable jTableDataLibros;
    // End of variables declaration//GEN-END:variables
}
