/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ManejoDeArchivos.BibliotecaCRUD;
import ManejoDeArchivos.LibroCRUD;
import epn.com.biblioteca.Biblioteca;
import epn.com.biblioteca.Libro;
import epn.com.biblioteca.Usuario;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thony
 */
public class MenuUsuario extends javax.swing.JFrame {
    private Usuario usuario = new Usuario(); 
    private LibroCRUD librosCRUD = new LibroCRUD(); 
    private BibliotecaCRUD biblioCrud = new BibliotecaCRUD();
    DefaultTableModel mt = new DefaultTableModel(); 
    
    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
        String ids [] = {"Titulo", "Autor", "Codigo", "Disponible"}; 
        mt.setColumnIdentifiers(ids);
        jTableLibros.setModel(mt);
        actualizarComboBoxBiblioteca();
        
    }
        public void actualizarComboBoxBiblioteca(){
        jCTiposBibliosUser.removeAllItems(); 
        List <Biblioteca> bibliotecas = biblioCrud.listarBibliotecas(); 
        if (bibliotecas.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se hay bibliotecas registradas");
        } else {
            for (Biblioteca b : bibliotecas){
            jCTiposBibliosUser.addItem(b.getNombre());
            }
        }
    }
        
    private void mostrarLibrosDeBiblioSeleccionada(){
       String nombreBiblio = (String) jCTiposBibliosUser.getSelectedItem(); 
        if (nombreBiblio == null || nombreBiblio.isBlank()) {
            JOptionPane.showMessageDialog(this, "Selecciona una biblioteca válida.");
            return;
        }
        List<Biblioteca> bibliotecas = biblioCrud.listarBibliotecas();
        boolean encontrada = false;
        for (Biblioteca b : bibliotecas){
            if (b.getNombre().trim().equalsIgnoreCase(nombreBiblio.trim())){
                cargarLibroEnTabla(b.getLibros());
                encontrada = true;
                break;
            }
        }

        if (!encontrada) {
            JOptionPane.showMessageDialog(this, "No se encontraron libros para la biblioteca seleccionada.");
        }
    }
    private void cargarLibroEnTabla(List<Libro> libros) {
    mt.setRowCount(0);
    for (Libro l : libros) {
        mt.addRow(new Object[]{
            l.getTitulo(),
            l.getAutor(),
            l.getCodigo(),
            l.isDisponible() ? "Sí" : "No"
        });
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBBuscarLibro = new javax.swing.JButton();
        jBMostrarPrestamos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        jTBuscar = new javax.swing.JTextField();
        jBMostrarLibros = new javax.swing.JButton();
        jBPrestamo = new javax.swing.JButton();
        jBDevolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCTiposBibliosUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Buscar libros:  ");

        jBBuscarLibro.setText("Buscar\n");
        jBBuscarLibro.setActionCommand("Buscar");
        jBBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarLibroActionPerformed(evt);
            }
        });

        jBMostrarPrestamos.setText("Mostrar Prestamos");
        jBMostrarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarPrestamosActionPerformed(evt);
            }
        });

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Codigo", "Disponible"
            }
        ));
        jScrollPane1.setViewportView(jTableLibros);

        jBMostrarLibros.setText("Mostrar Libros");
        jBMostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarLibrosActionPerformed(evt);
            }
        });

        jBPrestamo.setText("Pedir Prestamo");
        jBPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrestamoActionPerformed(evt);
            }
        });

        jBDevolver.setText("Devolver libro");
        jBDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverActionPerformed(evt);
            }
        });

        jLabel3.setText("¿En qué biblioteca deseas buscar? ");

        jCTiposBibliosUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona tu biblioteca..." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBMostrarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBMostrarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jBPrestamo)
                                .addGap(26, 26, 26)
                                .addComponent(jBDevolver)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCTiposBibliosUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBuscarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCTiposBibliosUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscarLibro))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMostrarPrestamos)
                    .addComponent(jBMostrarLibros))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPrestamo)
                    .addComponent(jBDevolver))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarLibroActionPerformed
    String textoBusqueda = jTBuscar.getText().trim().toLowerCase();
    String nombreBiblioteca = (String) jCTiposBibliosUser.getSelectedItem();

    if (nombreBiblioteca == null || nombreBiblioteca.equals("Selecciona tu biblioteca...")) {
        JOptionPane.showMessageDialog(this, "Selecciona una biblioteca primero.");
        return;
    }

    if (textoBusqueda.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Escribe el título o autor del libro a buscar.");
        return;
    }

    List<Biblioteca> bibliotecas = biblioCrud.listarBibliotecas();
    for (Biblioteca b : bibliotecas) {
        if (b.getNombre().equalsIgnoreCase(nombreBiblioteca)) {
            List<Libro> resultados = new ArrayList<>();
            for (Libro l : b.getLibros()) {
                if (l.getTitulo().toLowerCase().contains(textoBusqueda) ||
                    l.getAutor().toLowerCase().contains(textoBusqueda)) {
                    resultados.add(l);
                }
            }

            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron libros con ese criterio.");
            } else {
                cargarLibroEnTabla(resultados);
            }

            jTBuscar.setText("");
            return;
        }
    }

    JOptionPane.showMessageDialog(this, "Biblioteca no encontrada.");
    }//GEN-LAST:event_jBBuscarLibroActionPerformed

    private void jBMostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarLibrosActionPerformed
      mostrarLibrosDeBiblioSeleccionada();
    }//GEN-LAST:event_jBMostrarLibrosActionPerformed

    private void jBPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrestamoActionPerformed
    int filaSeleccionada = jTableLibros.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un libro de la tabla.");
        return;
    }

    String nombreBiblioteca = (String) jCTiposBibliosUser.getSelectedItem();
    String tituloLibro = (String) jTableLibros.getValueAt(filaSeleccionada, 0);

    List<Biblioteca> bibliotecas = biblioCrud.listarBibliotecas();
    for (Biblioteca b : bibliotecas) {
        if (b.getNombre().equalsIgnoreCase(nombreBiblioteca)) {
            for (Libro l : b.getLibros()) {
                if (l.getTitulo().equalsIgnoreCase(tituloLibro)) {
                    if (!l.isDisponible()) {
                        JOptionPane.showMessageDialog(this, "Este libro ya está prestado.");
                        return;
                    }

                    l.setDisponible(false);
                    biblioCrud.agregarBiblioteca(b); 
                    JOptionPane.showMessageDialog(this, "Préstamo realizado exitosamente.");
                    cargarLibroEnTabla(b.getLibros());
                    return;
                }
            }
        }
    }

    JOptionPane.showMessageDialog(this, "No se encontró el libro en la biblioteca seleccionada.");
    }//GEN-LAST:event_jBPrestamoActionPerformed

    private void jBDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverActionPerformed
    int filaSeleccionada = jTableLibros.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un libro de la tabla.");
        return;
    }

    String nombreBiblioteca = (String) jCTiposBibliosUser.getSelectedItem();
    String tituloLibro = (String) jTableLibros.getValueAt(filaSeleccionada, 0);

    List<Biblioteca> bibliotecas = biblioCrud.listarBibliotecas();
    for (Biblioteca b : bibliotecas) {
        if (b.getNombre().equalsIgnoreCase(nombreBiblioteca)) {
            for (Libro l : b.getLibros()) {
                if (l.getTitulo().equalsIgnoreCase(tituloLibro)) {
                    if (l.isDisponible()) {
                        JOptionPane.showMessageDialog(this, "Este libro ya está disponible.");
                        return;
                    }

                    l.setDisponible(true);
                    biblioCrud.agregarBiblioteca(b); 
                    JOptionPane.showMessageDialog(this, "Libro devuelto correctamente.");
                    cargarLibroEnTabla(b.getLibros());
                    return;
                }
            }
        }
    }

    JOptionPane.showMessageDialog(this, "No se encontró el libro en la biblioteca seleccionada.");
    }//GEN-LAST:event_jBDevolverActionPerformed

    private void jBMostrarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarPrestamosActionPerformed
               String nombreBiblioteca = (String) jCTiposBibliosUser.getSelectedItem();

    if (nombreBiblioteca == null || nombreBiblioteca.equals("Selecciona tu biblioteca...")) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una biblioteca.");
        return;
    }

    List<Biblioteca> bibliotecas = biblioCrud.listarBibliotecas();
    for (Biblioteca b : bibliotecas) {
        if (b.getNombre().equalsIgnoreCase(nombreBiblioteca)) {
            List<Libro> prestamos = new ArrayList<>();
            for (Libro l : b.getLibros()) {
                if (!l.isDisponible()) {
                    prestamos.add(l);
                }
            }

            if (prestamos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay libros prestados actualmente en esta biblioteca.");
            } else {
                cargarLibroEnTabla(prestamos);
            }
            return;
        }
    }

        JOptionPane.showMessageDialog(this, "Biblioteca no encontrada.");
    }//GEN-LAST:event_jBMostrarPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarLibro;
    private javax.swing.JButton jBDevolver;
    private javax.swing.JButton jBMostrarLibros;
    private javax.swing.JButton jBMostrarPrestamos;
    private javax.swing.JButton jBPrestamo;
    private javax.swing.JComboBox<String> jCTiposBibliosUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTable jTableLibros;
    // End of variables declaration//GEN-END:variables
}
