/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import ManejoDeArchivos.AccesoCRUD;
import ManejoDeArchivos.BibliotecarioCRUD;
import ManejoDeArchivos.UsuarioCRUD;
import epn.com.biblioteca.Acceso;
import epn.com.biblioteca.Bibliotecario;
import epn.com.biblioteca.Usuario;
import java.awt.CardLayout;
import java.awt.Panel;
import javax.swing.JOptionPane;

/**
 *
 * @author Thony
 */
public class VentanaRegistro extends javax.swing.JDialog {
    private UsuarioCRUD usuarioCRUD = new UsuarioCRUD(); 
    private BibliotecarioCRUD bibliotecarioCRUD = new BibliotecarioCRUD(); 
    private AccesoCRUD accesoCRUD = new AccesoCRUD();
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPPanelCambiante.setLayout(new CardLayout());
        jPPanelCambiante.add(jPanelUsuario, "Usuario"); 
        jPPanelCambiante.add(jPanelBibliotecario, "Bibliotecario"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGSub = new javax.swing.ButtonGroup();
        jPGeneral = new javax.swing.JPanel();
        jRol = new javax.swing.JComboBox<>();
        jPPanelCambiante = new javax.swing.JPanel();
        jPanelBibliotecario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTSalario = new javax.swing.JTextField();
        jCAreasTrabajo = new javax.swing.JComboBox<>();
        jCHorarios = new javax.swing.JComboBox<>();
        jPanelUsuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCTipoDocumento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jRSiSub = new javax.swing.JRadioButton();
        jRNoSub = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTTipoDocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTUsuarioRegistro = new javax.swing.JTextField();
        jBRegistrar = new javax.swing.JButton();
        jPContraRegistro = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPGeneral.setPreferredSize(new java.awt.Dimension(500, 400));

        jRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol...", "Bibliotecario", "Usuario", " " }));
        jRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRolActionPerformed(evt);
            }
        });

        jPPanelCambiante.setLayout(new java.awt.CardLayout());

        jLabel7.setText("Area de trabajo");

        jLabel8.setText("Salario");

        jLabel9.setText("Horario");

        jCAreasTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepción", "Busqued", "Prestamos y devoluciones", "Procesos tecnicos" }));

        jCHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Turno Completo" }));

        javax.swing.GroupLayout jPanelBibliotecarioLayout = new javax.swing.GroupLayout(jPanelBibliotecario);
        jPanelBibliotecario.setLayout(jPanelBibliotecarioLayout);
        jPanelBibliotecarioLayout.setHorizontalGroup(
            jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTSalario)
                    .addComponent(jCAreasTrabajo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCHorarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanelBibliotecarioLayout.setVerticalGroup(
            jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCAreasTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBibliotecarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jCHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPPanelCambiante.add(jPanelBibliotecario, "Bibliotecario");

        jPanelUsuario.setPreferredSize(new java.awt.Dimension(150, 300));

        jLabel10.setText("Tipo de documento");

        jCTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte", "Carnet Estudiantil" }));

        jLabel11.setText("¿Suscripción Activa?");

        bGSub.add(jRSiSub);
        jRSiSub.setText("Si");

        bGSub.add(jRNoSub);
        jRNoSub.setText("No");

        jLabel12.setText("Digite el tipo de documento");

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(23, 23, 23)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addComponent(jRSiSub)
                        .addGap(18, 18, 18)
                        .addComponent(jRNoSub))
                    .addComponent(jCTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTTipoDocumento))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRSiSub)
                            .addComponent(jRNoSub)))
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPPanelCambiante.add(jPanelUsuario, "Usuario");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("R E G I S T R O ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Rol");

        jLabel3.setText("Nombre");

        jLabel4.setText("Telefono");

        jLabel5.setText("Usuario (Log in)");

        jLabel6.setText("Contraseña");

        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGeneralLayout = new javax.swing.GroupLayout(jPGeneral);
        jPGeneral.setLayout(jPGeneralLayout);
        jPGeneralLayout.setHorizontalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPPanelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPGeneralLayout.createSequentialGroup()
                                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(81, 81, 81)
                                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRol, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jTNombre)
                                    .addComponent(jTTelefono)
                                    .addComponent(jTUsuarioRegistro)
                                    .addComponent(jPContraRegistro)))))
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jBRegistrar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPGeneralLayout.setVerticalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jPContraRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPPanelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRolActionPerformed
        CardLayout card = (CardLayout) jPPanelCambiante.getLayout(); 
        String rol = (String) jRol.getSelectedItem(); 
        card.show(jPPanelCambiante, rol);
    }//GEN-LAST:event_jRolActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed
        String nombre = jTNombre.getText(); 
        String telefono = jTTelefono.getText(); 
        String usuarioRegistro = jTUsuarioRegistro.getText(); 
        String contrasena = new String(jPContraRegistro.getPassword());
        Acceso acceso = new Acceso(usuarioRegistro, contrasena);
        accesoCRUD.agregarAcceso(acceso);
        String rol = (String) jRol.getSelectedItem(); 
        
        if("Usuario".equals(rol)){
            String tipoDocumento = (String) jCTipoDocumento.getSelectedItem(); 
            String documentoDigito = jTTipoDocumento.getText(); 
            boolean subActiva; 
            if (jRSiSub.isSelected()){
                subActiva = true; 
            } else {
                subActiva = false; 
            }
            Usuario usuarioNuevo = new Usuario(nombre, telefono, acceso, tipoDocumento, documentoDigito, subActiva);
            usuarioCRUD.agregarUsuario(usuarioNuevo);
            JOptionPane.showMessageDialog(null, "Usuario registrado con existo", "Exito en el registro",1);
        } else if ("Bibliotecario".equals(rol)){
            String areaTrabajo = (String) jCAreasTrabajo.getSelectedItem();
            Double salario = Double.valueOf(jTSalario.getText()); 
            String horario = (String) jCHorarios.getSelectedItem();
            Bibliotecario biblio = new Bibliotecario(nombre, telefono, acceso, areaTrabajo, salario, horario);
            bibliotecarioCRUD.agregarBiblitecario(biblio);
            JOptionPane.showMessageDialog(null, "Bibliotecario registrado con existo", "Exito en el registro",1);

        }
        
        
        jTNombre.setText("");
        jTTelefono.setText("");
        jTUsuarioRegistro.setText("");
        jPContraRegistro.setText("");
        jRol.setSelectedIndex(0);
        jCTipoDocumento.setSelectedIndex(0);
        jRSiSub.setSelected(false);
        jRNoSub.setSelected(false);
        jCAreasTrabajo.setSelectedIndex(0);
        jCHorarios.setSelectedIndex(0);
        jTSalario.setText("");
        
    }//GEN-LAST:event_jBRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistro dialog = new VentanaRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGSub;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JComboBox<String> jCAreasTrabajo;
    private javax.swing.JComboBox<String> jCHorarios;
    private javax.swing.JComboBox<String> jCTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPContraRegistro;
    private javax.swing.JPanel jPGeneral;
    private javax.swing.JPanel jPPanelCambiante;
    private javax.swing.JPanel jPanelBibliotecario;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JRadioButton jRNoSub;
    private javax.swing.JRadioButton jRSiSub;
    private javax.swing.JComboBox<String> jRol;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTSalario;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTextField jTTipoDocumento;
    private javax.swing.JTextField jTUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
